#! /bin/sh
### BEGIN INIT INFO
# Provides:          mongodb_configsvr
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MongoDB cluster configuration server
# Description:       Starts a configuration server that holds meta data
#                    for a MongoDB cluster.
### END INIT INFO

# Author: Fabian Reinartz <fab.reinartz@gmail.com>

PATH=/bin:/usr/bin
DESC="mongodb configuration server for sharding"
NAME=mongod
BIN=/opt/mongodb/mongodb/bin/$NAME
CONF=/opt/mongodb/epidb/src/epidb/mongo/etc/mongod_configsvr.conf

# Exit if the binary is not installed
[ -x "$BIN" ] || { echo "$BIN not found"; exit 0; }

# Read configuration variable file if it is present, exit otherwise
[ -r $CONF ] && . $CONF || { echo "$CONF not found"; exit 0; }
 
do_start()
{
if [ -r $PIDFILEPATH ]; then
    PID=$(cat $PIDFILEPATH)
  fi
  if [ -n "$PID" ] && ps -p $PID > /dev/null; then
    echo "mongod config server already running"
    exit 0
   else
	echo "starting mongodb configuration server on port $PORT"
	echo "cmd: $BIN -configsvr -fork -port $PORT --nssize 2047 -dbpath $DBPATH -logpath $LOGPATH -pidfilepath $PIDFILEPATH"
	$BIN -configsvr -fork -port $PORT --nssize 2047 -dbpath $DBPATH -logpath $LOGPATH -pidfilepath $PIDFILEPATH
  fi
}

do_stop()
{
	echo "checking if mongod config server is running"
	if [ -r $PIDFILEPATH ]; then
		PID=$(cat $PIDFILEPATH)
	fi
	if [ -z "$PID" ]; then
		echo "mongod config server not running"; exit 0
	fi
	echo "stopping mongod config server"
	kill -2 $PID
	rm -f $PIDFILEPATH
}


case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
  ;;
  *)
	echo "Usage: $0 {start|stop}" >&2
	exit 3
	;;
esac

:
