#! /bin/sh
### BEGIN INIT INFO
# Provides:          deepblue
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DeepBlue Start shards
# Description:       Starts DeepBlue Epigenomic Data Server
### END INIT INFO

# Author: Felipe Albrecht <felipe.albrecht@mpi-inf.mpg.de>

PATH=/bin:/usr/bin
DESC="deepblue deamon"
NAME=server
BIN=/local/data/DeepBlue/server/src/$NAME
# Exit if the binary is not installed
[ -x "$BIN" ] || { echo "$BIN not found"; exit 0; }

# Read configuration variable file if it is present, exit otherwise
[ -r $CONF ] && . $CONF || { echo "$CONF not found"; exit 0; }

do_start()
{
  if [ -r $PIDFILEPATH ]; then
    local PID=$(cat $PIDFILEPATH)
  fi
  if [ -n "$PID" ] && ps -p $PID > /dev/null; then
    echo "deepblue server is already running"
    return 2
  else
    echo "starting deepblue server"
    echo "nohup $BIN -A 0.0.0.0 -P $PORT -M $MONGDB -D $DATABASE  -T $THREADS -X > $LOGPATH &"
    nohup $BIN -A 0.0.0.0 -P $PORT -M $MONGDB -D $DATABASE  -T $THREADS -X > $LOGPATH &
    echo $! > $PIDFILEPATH
  fi

  return 0
}

do_stop()
{
  echo "checking if deepblue server is running"
  if [ -r $PIDFILEPATH ]; then
    local PID=$(cat $PIDFILEPATH)
  fi
  if [ -z "$PID" ]; then
    echo "deepblue server is not running"
    return 2
  fi
  echo "stopping deepblue server"
  kill -2 $PID
  rm -f $PIDFILEPATH
  return 0
}

case "$1" in
  start)
  do_start $2
  ;;
  stop)
  do_stop $2
  ;;
  *)
  echo "Usage: $0 {start|stop}" >&2
  exit 3
  ;;
esac

:
